config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:index, :show, :update] do
    collection do # don't know why I need this
      get :autocomplete
    end
  end

  resources :wikis do
    resources :collaborations, only: [:index, :create, :destroy]
    collection do # don't know why I need this
      get :autocomplete
    end
  end

  resources :memberships, only: [:new, :create, :destroy]

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  namespace :stripe do
    resources :subscription_events, only: :create
  end

  get 'welcome/about'

  root 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  searchkick autocomplete: ['username']
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one  :membership
  has_many :wikis
  has_many :collaborations
  has_many :shared_wikis, through: :collaborations, source: :wiki

  enum role: [:standard, :premium, :admin]

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

before_action :configure_permitted_params, only: [:create, :update]

protected

def configure_permitted_params

  added_attributes = [:username,
                      :email,
                      :password,
                      :password_confirmation,
                      :role,
                      :remember_me]

  devise_parameter_sanitizer.permit(:sign_up, keys: added_attributes)
  devise_parameter_sanitizer.permit(:account_update, keys: added_attributes)
end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def autocomplete
    render json: User.search(params[:query], autocomplete: true, limit: 10).map do |user|
      { username: user.username, value: user.id }
    end
  end
end

app/views/users/show.html.erb
<br/>

<div class="media-left">
  <%= gravatar_url(current_user, 128) %>
</div>

<div class="media-body">
  <div class="pull-right">

    <%= link_to "Edit Your Details", edit_user_registration_path, class: 'btn btn-primary' %>

    <% if current_user.standard? %>
      <%= link_to "Upgrade to Premium", new_membership_path, class: 'btn btn-primary' %>
    <% elsif current_user.premium? %>
      <%= link_to "Downgrade to Standard", membership_path(current_user),
        data: { confirm: "Are you sure? All your private Wikis will be made public" },
          method: :delete, class: 'btn btn-primary' %>
    <% end %>

  </div>

    <h2 class="media-heading"><%= current_user.username %></h2>
    <small>
      <%= pluralize(current_user.wikis.count, 'wiki') %> created <br/>
      Member since <%=current_user.created_at.strftime("%B %d, %Y") %>
    </small>

  </div>

<div class="row">
  <div class="col-md-8">
  <br/>

  <h4 class="media-heading">Your Public Wikis...</h4>
    <% current_user.wikis.where(private: false).each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h5 class="media-heading"><%= link_to wiki.title, wiki_path(wiki) %></h5>
            <small><%= wiki.body.truncate_words(15) %></small>
        </div>
      </div>
    <% end %>

  <br/>

  <h4 class="media-heading">And Your Private Wikis...</h4>
    <% if current_user.standard? %>
      <p>You need a Premium membership to use private Wikis. Subscribe above!</p>
    <% else %>
      <% current_user.wikis.where(private: true).each do |wiki| %>
        <div class="media">
          <div class="media-body">
            <h5 class="media-heading"><%= link_to wiki.title, wiki_path(wiki) %></h5>
              <small><%= wiki.body.truncate_words(15) %></small>
          </div>
        </div>
      <% end %>
    <% end %>

  </div>
</div>