config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:index, :show, :update] do
    collection do # don't know why I need this
      get :autocomplete
    end
  end

  resources :wikis do
    resources :collaborations, only: [:index, :create, :destroy]
    collection do # don't know why I need this
      get :autocomplete
    end
  end

  resources :memberships, only: [:new, :create, :destroy]

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  namespace :stripe do
    resources :subscription_events, only: :create
  end

  get 'welcome/about'

  root 'welcome#index'
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  searchkick autocomplete: ['title']

  belongs_to :user
  has_many   :collaborations
  has_many   :collaborating_users, through: :collaborations, source: :user

  default_scope { order('updated_at DESC') }
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  before_action :authenticate_user!

  def index
    if params[:query].present?
      @wikis = Wiki.search(params[:query]) #not sure how to combine with Pundit
    else
      @wikis = policy_scope(Wiki)
    end
  end

  def autocomplete
    render json: Wiki.search(params[:query], autocomplete: true, limit: 10).map do |wiki|
      { title: wiki.title, value: wiki.id }
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)

    if @wiki.save
      flash[:notice] = "Your Wiki has been created successfully"
      redirect_to @wiki
    else
      flash[:alert] = "Wiki creation was unsuccessful. Please try again."
      redirect_to new_wiki_path
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.update(wiki_params)
      flash[:notice] = "Your Wiki was successfully updated"
      redirect_to wiki_path
    else
      flash[:alert] = "There was an error updating you Wiki. Please try again."
      redirect_to edit_wiki_path
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "You Wiki was successfully deleted"
      redirect_to wikis_path
    else
      flash[:alert] = "There was an error deleting this Wiki. Please try again."
      redirect_to wiki_path
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/wikis_helper.rb
module WikisHelper

end

app/views/wikis/edit.html.erb
<h1>Edit this Wiki</h1>
<br/>
<div class="row">
  <div class="col-md-8">

    <%= form_for @wiki do |f| %>
    <!-- use form_group_tag from ApplicationHelper to display errors -->
      <%= form_group_tag(@wiki.errors[:title]) do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title here" %>
      <% end %>

      <%= form_group_tag(@wiki.errors[:body]) do %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 12, class: 'form-control body-text', placeholder: "Enter your Wiki text here" %>
      <% end %>

    <div class="form-group">
      <div id="preview_text"></div>
    </div>

  </div>
</div>

  <div class="col-md-8">
    <div class="row">
      <% if authorize_view_element %>
          <%= f.label :private, class: 'checkbox col-md-8' do %>
            <%= f.check_box :private %> Private Wiki
          <% end %>
      <% end %>
    </div>

    <div class="row">
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    </div>

    <% end %>
  </div>

app/views/wikis/index.html.erb
<div class="media-left">
  <h1>Wikis</h1>
</div>

<div class="media-body">
  <div class="pull-right">
    <br/>

    <%= link_to "Create Wiki", new_wiki_path, class: 'btn btn-primary' %>
    <% if current_user.standard? %>
      <%= link_to "Upgrade to Premium", new_membership_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>
<br/>

<div class="form-group form-narrow">
  <%= form_tag wikis_path, method: :get do %>
    <%= text_field_tag :query, params[:query], class: 'form-control search-wiki'%>
    <%= submit_tag 'Search', class: 'btn btn-primary' %>
  <% end %>
</div>

<br/>

<div class="row">
  <div class="col-md-8">

    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading"><%= link_to wiki.title, wiki_path(wiki) %></h4>
          <small><%= wiki.body.truncate_words(15) %></small>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>Create a new Wiki</h1>
<br/>
<div class="row">
  <div class="col-md-8">

    <%= form_for @wiki do |f| %>
    <!-- use form_group_tag from ApplicationHelper to display errors -->
      <%= form_group_tag(@wiki.errors[:title]) do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title here" %>
      <% end %>

      <%= form_group_tag(@wiki.errors[:body]) do %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: "Enter your Wiki text here" %>
      <% end %>

    <div class="form-group">
      <div id="preview_text"></div>
    </div>

  </div>
</div>

  <div class="col-md-8">
    <div class="row">
      <% if authorize_view_element %>
          <%= f.label :private, class: 'checkbox col-md-4' do %>
            <%= f.check_box :private %> Private Wiki
          <% end %>
      <% end %>
    </div>

    <div class="row">
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    </div>

    <% end %>
  </div>

app/views/wikis/show.html.erb
<h1>
  <%= @wiki.title %><br/>
  <small>created <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.username %></small>
</h1>

<div class="row">
  <div class="col-md-8">
    <div id='show_wiki'><%= @wiki.body %></div>
  </div>
</div>

  <br/>

    <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-primary' %>
    <% if authorize_view_element %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger',
        data: { confim: "Are you sure you want to delete this Wiki?" } %>
    <% end %>


    <div class="media">
      <h5><%= list_collaborators(@wiki.collaborating_users, @wiki) %>

      <% if authorize_view_element %>
        <% if @wiki.collaborating_users.any? %>
          <%= link_to "Remove someone", wiki_collaborations_path(@wiki) %> or add more collaborators below:
        <% end %>
      </h5>

        <div class="form-group">
          <%= form_tag wiki_collaborations_path(@wiki), method: :post do %>
            <%= text_field_tag :query, params[:query], class: 'form-control search-user' %>
            <%= submit_tag 'Add', class: 'btn btn-primary' %>
          <% end %>
        </div>

      <% end %>
    </div>