config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:index, :show, :update] do
    collection do # don't know why I need this
      get :autocomplete
    end
  end

  resources :wikis do
    resources :collaborations, only: [:index, :create, :destroy]
    collection do # don't know why I need this
      get :autocomplete
    end
  end

  resources :memberships, only: [:new, :create, :destroy]

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  namespace :stripe do
    resources :subscription_events, only: :create
  end

  get 'welcome/about'

  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= notice %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= alert %>
        </div>
      <% end %>
    </div>

    <ul class="nav nav-tabs">

      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>

    <% if user_signed_in? %>
      <div class="pull-right user-info">
        <%= gravatar_url(current_user, 35) %>
        <div class="pull-right">
          <%= link_to current_user.username, user_path(current_user), class: "navbar-link" %><br/>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-link" %>
        </div>
      </div>
    <% else %>
      <li class="pull-right"><%= link_to "Sign Up", new_user_registration_path %></li>
      <li class="pull-right"><%= link_to "Sign In", new_user_session_path %></li>
    <% end %>
    </ul>

<%= yield %>

</body>
</html>